### ISSUE TITLE
many errors, i am horrible at coding

### ISSUE THREAD

**Issue by pwm74** [nygma2004/Wifi_LokRemote#2]
hey sorry to bother you. after many attempts i tried to implement this code. i am a old guy who is not good at fixing errors. one of the many errors i get is "Compilation error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?"  i am in over my head. i have succesfully downloaded many codes to arduino projects throught the years but this is a tough one.  is there anyway you can help me out. thanks

**Comment by nygma2004** [comment]
I have not touched this project for a while, give me a bit of time to take a look.

**Comment by pwm74** [comment]
very nice, thank you

**Comment by nygma2004** [comment]
It looks like some of the libraries have changed since, and I am getting the same errors as you. I made some quick change of the code and now it compiles. But I have not tested it, and I may have broken something.

1st change: this is where you got the errors. I commented out the old lines with `/*` and `*/` and added two new lines in:
```
/* old code
  ledcAttachPin(MOTORIN1,0);  // assign the speed control PWM pin to a channel
  ledcAttachPin(MOTORIN2,1);  // assign the speed control PWM pin to a channel
   
  // initialize channel 0-15, resolution 1-16 bit, frequency limit depend on resolution
  ledcSetup(0,PWMFREQ,8);  // channel- 0, frequency- 4000, Resolution bit- 8
  ledcSetup(1,PWMFREQ,8);  // channel- 0, frequency- 4000, Resolution bit- 8
*/
  ledcAttach(MOTORIN1, 5000, 8);
  ledcAttach(MOTORIN2, 5000, 8);
```

2nd change: for me these are line 769-771, and I commented out these lines with `//`:
```
    //TIMERG0.wdtwprotect=TIMG_WDT_WKEY_VALUE;
    //TIMERG0.wdtfeed=1;
    //TIMERG0.wdtwprotect=0;
```

Can you make these changes yourself as well and test?

**Comment by pwm74** [comment]
Thank you for the reply
it compiled and uploaded to board. however i do not see its wifi network
and the board just shows a red solid led.

**Comment by nygma2004** [comment]
Can you power the board by the USB on the ESP32 and use the serial monitor of the Arduino IDE to see the series console to see the messages coming out of the ESP?

**Comment by pwm74** [comment]
yes, however it is a quick scrolling of this

ho 8 tail 4 room 4
load:0x40080404,len:3524
entry 0x400805b8
E (336) ADC: CONFLICT! driver_ng is not allowed to be used with the legacy driver

**Comment by pwm74** [comment]
other examples do work on my current board.

**Comment by pwm74** [comment]
Any luck in fixing?

**Comment by nygma2004** [comment]
I was away for Christmas and the New Year, so did not have much time. To be honest I only had time to check if I can compile project and did not test it. I need more time on this, but does not look like an obvious issue.

**Comment by pwm74** [comment]
Very good. When you have the time and if possible. Thank you and Happy New year.

**Comment by nygma2004** [comment]
Sorry for a very late reply, I am still not done with all the testing (my test board which I used for testing does not seem to work now). But I managed to re-compile the code, and it works, I can see the webpage and everything. And with this, I was using the original code which is on github, without the modification I said above.

I got my old laptop working where I did the development and it has the following environment:
- Arduino IDE 1.8.13: this will most probably work with the latest 1.8.x version, but this is where I tested. This 1.8.x version is important, becauset the data upload plugin does not work in 2.x. But you can download older versions and install it.
- This artivle explains how to install the plugin for the uploader. We are using ESP32, so you only need to install that: https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/
- In Arduino IDE under File / Preferences, this is the URL I used for Boards Manager URLs: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
- Under Tools / Board / Board Manager, esp32 by Espressif Systems is installed, version 2.0.6
- Under Tools / Manager Libraries I have the following installed
  - ArduinoJson by Benoit Blanchon: 6.18.5
  - ESP8266Audio by Earle F. Philhower: 2.0.0
-  Under Tools, this is how I have the board configured
  - Board / ESP32 Arduino / ESP32 Dev Module
  - Partition Scheme: No OTA (1MB App/3MB SPIFFS)
  - rest is default

With these you can compile the code and upload to the ESP. I sometimes get and error that the ipload fails, in that case I click upload again, and press the boot button on the board for 1 second when the dots are appearing.

I have uploaded my `data` folder to this project which contains some sample audio and also a json which you can configure initially. This has to be in the data folder in the project. Now that the sketch is uploaded to the ESP, you can select Tools / ESP32 Sketch Data Upload and it will upload the audio and the config file to the ESP's memory. Upload may fail if you have the serial monitor open. You may also need to press the boot button if it does not work. Sometimes I get a upload error with some `Invalid head of packet` error, but I try again and usually works second time.

One more comment on the config.json: it has a `wifimode` settings in it which is set to `sta`. This tells the ESP to connect to the wifi using the `ssid` and `password`. This will connect to your wifi if you set it correctly. I think it is good for testing. Otherwise set the `wifimode` to `ap` so the ESP creates its own wifi.

If this all goes well, your that should be all the software setup. I usually connect the ESP to my computer using the USB cable and use the Serial Monitor to check all the messages, if it reads all the sound files, what IP it connects to, etc.

Let me know how it goes.

**Comment by goose715** [comment]
hi , 
kinda stuck on ide 1.8 errors listed below any help would be great 
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: sketch\Wifi_LokRemote_copy_wednesday2april_editted.ino.cpp.o:(.literal._Z7PlayWAVPKcb+0x4c): undefined reference to `AudioFileSourceSPIFFS::AudioFileSourceSPIFFS(char const*)'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: sketch\Wifi_LokRemote_copy_wednesday2april_editted.ino.cpp.o:(.literal._Z17loadConfigurationPKcR6Config6String+0xc): undefined reference to `SPIFFS'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: sketch\Wifi_LokRemote_copy_wednesday2april_editted.ino.cpp.o:(.literal._Z5setupv+0xd0): undefined reference to `fs::SPIFFSFS::begin(bool, char const*, unsigned char, char const*)'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: sketch\Wifi_LokRemote_copy_wednesday2april_editted.ino.cpp.o: in function `PlayWAV(char const*, bool)':
G:\new wifi train\Wifi_LokRemote_copy_wednesday2april_editted/Wifi_LokRemote_copy_wednesday2april_editted.ino:480:(.text._Z7PlayWAVPKcb+0xbe): undefined reference to `AudioFileSourceSPIFFS::AudioFileSourceSPIFFS(char const*)'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: sketch\Wifi_LokRemote_copy_wednesday2april_editted.ino.cpp.o: in function `setup()':
G:\new wifi train\Wifi_LokRemote_copy_wednesday2april_editted/Wifi_LokRemote_copy_wednesday2april_editted.ino:651:(.text._Z5setupv+0x132): undefined reference to `fs::SPIFFSFS::begin(bool, char const*, unsigned char, char const*)'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
 Used: C:\Users\jbenn\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.2.0\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\jbenn\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.2.0\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board ESP32 Wrover Kit (all versions).

**Comment by goose715** [comment]
hi, tried many ways to compile in 1.8 but many errors and decided to try the later 2.x versions not concerned about sound at this poing and just would like the shuttle and station stop to run error log below if you can shed any light 
thanks 
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: C:\Users\jbenn\AppData\Local\arduino\sketches\C4355D1A57BB5B1A4B4A5F8865346638\sketch\objs.a(Wifi_LokRemote_friday4april.ino.cpp.o):(.literal._Z7PlayWAVPKcb+0x4c): undefined reference to `AudioFileSourceSPIFFS::AudioFileSourceSPIFFS(char const*)'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: C:\Users\jbenn\AppData\Local\arduino\sketches\C4355D1A57BB5B1A4B4A5F8865346638\sketch\objs.a(Wifi_LokRemote_friday4april.ino.cpp.o):(.literal._Z17loadConfigurationPKcR6Config6String+0xc): undefined reference to `SPIFFS'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: C:\Users\jbenn\AppData\Local\arduino\sketches\C4355D1A57BB5B1A4B4A5F8865346638\sketch\objs.a(Wifi_LokRemote_friday4april.ino.cpp.o):(.literal._Z5setupv+0xd0): undefined reference to `fs::SPIFFSFS::begin(bool, char const*, unsigned char, char const*)'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: C:\Users\jbenn\AppData\Local\arduino\sketches\C4355D1A57BB5B1A4B4A5F8865346638\sketch\objs.a(Wifi_LokRemote_friday4april.ino.cpp.o): in function `PlayWAV(char const*, bool)':
G:\new wifi train\test on toshiba laptop\Wifi_LokRemote_friday4april/Wifi_LokRemote_friday4april.ino:484:(.text._Z7PlayWAVPKcb+0xbe): undefined reference to `AudioFileSourceSPIFFS::AudioFileSourceSPIFFS(char const*)'
C:/Users/jbenn/AppData/Local/Arduino15/packages/esp32/tools/esp-x32/2411/bin/../lib/gcc/xtensa-esp-elf/14.2.0/../../../../xtensa-esp-elf/bin/ld.exe: C:\Users\jbenn\AppData\Local\arduino\sketches\C4355D1A57BB5B1A4B4A5F8865346638\sketch\objs.a(Wifi_LokRemote_friday4april.ino.cpp.o): in function `setup()':
G:\new wifi train\test on toshiba laptop\Wifi_LokRemote_friday4april/Wifi_LokRemote_friday4april.ino:659:(.text._Z5setupv+0x132): undefined reference to `fs::SPIFFSFS::begin(bool, char const*, unsigned char, char const*)'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
  Used: C:\Users\jbenn\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.2.0\libraries\SD
  Not used: C:\Users\jbenn\AppData\Local\Arduino15\libraries\SD
exit status 1

**Comment by goose715** [comment]
i can get it to upload but cannot get past thiserror 
E (401) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
E (410) esp_core_dump_elf: Elf write init failed!
E (414) esp_core_dump_common: Core dump write failed with error=-1
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4660
load:0x40078000,len:15576
load:0x40080400,len:4
load:0x40080404,len:3152
entry 0x400805a0
E (382) ADC: CONFLICT! driver_ng is not allowed to be used with the legacy driver
